services:
  api:
    build:
      context: src/Tempo.Api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GeocodingApi__BaseUrl=http://mock:3000/
      - WeatherApi__BaseUrl=http://mock:3000/
    depends_on:
      - mock

  mock:
    build:
      context: mocks
    ports:
      - "3000:3000"
